# NOTE: Run command:
# docker compose -f 'docker-compose.yml' up --build --force-recreate --remove-orphans
# Compose down:
# docker compose -f 'docker-compose.yml' down --remove-orphans --volumes --rmi all

services:
  nodejs-template:
    image: nodejs-template-prod
    container_name: nodejs-template-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/usr/src/app/logs
